# Generated by Django 5.0.3 on 2024-04-11 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_prediction_predicted_entry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='predicted_entry',
            name='risk_of_rain',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
