# Generated by Django 5.0.3 on 2024-04-16 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_predicted_entry_risk_of_rain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicted_entry',
            name='dwpt',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='predicted_entry',
            name='pres',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='predicted_entry',
            name='rhum',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='predicted_entry',
            name='risk_of_rain',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='predicted_entry',
            name='temp',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='predicted_entry',
            name='wdir',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='predicted_entry',
            name='wspd',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=10),
        ),
    ]
