# Generated by Django 5.0.3 on 2024-03-26 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='value',
        ),
        migrations.AddField(
            model_name='entry',
            name='coco',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(27)]),
        ),
        migrations.AddField(
            model_name='entry',
            name='dwpt',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=6),
        ),
        migrations.AddField(
            model_name='entry',
            name='prcp',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=6),
        ),
        migrations.AddField(
            model_name='entry',
            name='pres',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=6),
        ),
        migrations.AddField(
            model_name='entry',
            name='rhum',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=6),
        ),
        migrations.AddField(
            model_name='entry',
            name='temp',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=6),
        ),
        migrations.AddField(
            model_name='entry',
            name='time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='wdir',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=6),
        ),
        migrations.AddField(
            model_name='entry',
            name='wspd',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=6),
        ),
    ]
