# Generated by Django 5.0.3 on 2024-03-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_remove_entry_name_remove_entry_value_entry_coco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
