# Generated by Django 5.0.3 on 2024-04-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alter_predicted_entry_dwpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicted_entry',
            name='dwpt',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='predicted_entry',
            name='pres',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='predicted_entry',
            name='rhum',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='predicted_entry',
            name='temp',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='predicted_entry',
            name='wdir',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='predicted_entry',
            name='wspd',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=6),
        ),
    ]
